# Generated by Django 3.0.3 on 2020-05-13 21:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodblogpost',
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='foodcomment',
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
    ]
