# Generated by Django 3.0.3 on 2020-05-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_foodimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodblogpost',
            old_name='post',
            new_name='section_1',
        ),
        migrations.AddField(
            model_name='foodblogpost',
            name='section_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foodblogpost',
            name='section_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foodblogpost',
            name='section_4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foodblogpost',
            name='section_5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foodblogpost',
            name='section_6',
            field=models.TextField(null=True),
        ),
    ]
