# Generated by Django 3.0.3 on 2020-05-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_auto_20200515_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodblogpost',
            name='section_1',
        ),
        migrations.RemoveField(
            model_name='foodblogpost',
            name='section_2',
        ),
        migrations.RemoveField(
            model_name='foodblogpost',
            name='section_3',
        ),
        migrations.RemoveField(
            model_name='foodblogpost',
            name='section_4',
        ),
        migrations.RemoveField(
            model_name='foodblogpost',
            name='section_5',
        ),
        migrations.RemoveField(
            model_name='foodblogpost',
            name='section_6',
        ),
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField()),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Food.FoodBlogPost')),
            ],
        ),
    ]
